language: go
sudo: required

go:
  - 1.12

env:
  - ChubaoFS_BUILD_BASE="chubaofs/chubaofs-build:1.0"

services: docker

notifications:
  on_success: never
  on_failure: never

before_install:
  - docker pull ${ChubaoFS_BUILD_BASE}

script:
  - docker run --rm -v `pwd`:/go/src/github.com/chubaofs/cfs ${ChubaoFS_BUILD_BASE} /bin/bash -c "cd /go/src/github.com/chubaofs/chubaofs && make build"

