{
 "title": "ChubaoFS",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "cfs" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{app=\"$app\"}, cluster)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(up{app=\"$app\", cluster=\"$cluster\"}, role)"
   },
   { "name": "topk", "label": "topK", "query": "5,10,20,30,50,100" },
   {
    "name": "mnOp",
    "label": "MetaNodeOp",
    "query": "OpMetaCreateInode, OpMetaLinkInode, OpMetaFreeInodesOnRaftFollower, OpMetaUnlinkInode, OpMetaInodeGet, OpMetaEvictInode, OpMetaSetattr, OpMetaCreateDentry, OpMetaDeleteDentry, OpMetaUpdateDentry, OpMetaReadDir, OpCreateMetaPartition, OpMetaNodeHeartbeat, OpMetaExtentsAdd, OpMetaExtentsList, OpMetaExtentsDel, OpMetaTruncate, OpMetaLookup, OpDeleteMetaPartition, OpUpdateMetaPartition, OpLoadMetaPartition, OpDecommissionMetaPartition, OpAddMetaPartitionRaftMember, OpRemoveMetaPartitionRaftMember, OpMetaPartitionTryToLeader, OpMetaBatchInodeGet, OpMetaDeleteInode, OpMetaBatchExtentsAdd, OpMetaSetXAttr, OpMetaGetXAttr, OpMetaBatchGetXAttr, OpMetaRemoveXAttr, OpMetaListXAttr, OpCreateMultipart, OpListMultiparts, OpRemoveMultipart, OpAddMultipartPart, OpGetMultipart"
   },
   {
    "name": "dnOp",
    "label": "DataNodeOp",
    "query": "OpCreateExtent,OpWrite,OpSyncWrite,OpStreamRead,OpStreamFollowerRead,OpExtentRepairRead,OpMarkDelete,OpRandowWrite,OpSyncRandomWrite,OpNotifyReplicasToRepair,OpGetAllWatermarks,OpCreateDataPartition,OpLoadDataPratition,OpDeleteDataPartition,OpDataNodeHeartbeat,OpGetAppliedId,OpDecommissionDataPartition,OpAddDataPartitionRaftMember,OpDataPartitionTryToLeader,OpGetPartitionSize,OpGetMaxExtentIDAndPartitionSize,OpReadTinyDeleteRecord,OpBroadcastMinAppliedID"
   },
   {
    "name": "fuseOp",
    "label": "fuseOp",
    "query": "mkdir,mknod,filecreate,link,symlink,rmdir,unlink,readdir,rename,fileread,filewrite,filesync"
   },
   {
    "name": "obOp",
    "label": "objectNodeOp",
    "query": "GetObject, PutObject, CopyObject, ListObjects, DeleteObject, DeleteObjects, HeadObject, CreateBucket, DeleteBucket, HeadBucket, ListBuckets, GetBucketPolicy, PutBucketPolicy, DeleteBucketPolicy, GetBucketAcl, PutBucketAcl, GetObjectAcl, PutObjectAcl, CreateMultipartUpload, ListMultipartUploads, UploadPart, ListParts, CompleteMultipartUpload, AbortMultipartUpload, GetBucketLocation, GetObjectXAttr, PutObjectXAttr, ListObjectXAttrs, DeleteObjectXAttr, GetObjectTagging, PutObjectTagging, DeleteObjectTagging, GetBucketTagging, PutBucketTagging, DeleteBucketTagging, Read, Write,"
   },
   {
    "name": "vol",
    "label": "Vol",
    "query": "label_values(cfs_master_vol_total_GB{app=\"$app\",cluster=\"$cluster\"}, volName)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{app=\"$app\", role=\"$role\", cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "hostip",
    "label": "Host",
    "query": "label_values(go_info{instance=\"$instance\", cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "master_instance",
    "label": "MasterInstance",
    "query": "label_values(up{app=\"$app\", role=\"master\", cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MasterCount",
   "type": "singlestat",
   "description": "master node total count of cluster",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{cluster=\"$cluster\", app=\"$app\", role=\"master\"} > 0)"
    }
   ]
  },
  {
   "title": "MetaNodeCount",
   "type": "singlestat",
   "description": "Metanode total count for current selected cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{cluster=\"$cluster\", app=\"$app\", role=\"metanode\"} > 0)"
    }
   ]
  },
  {
   "title": "DataNodeCount",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{cluster=\"$cluster\", app=\"$app\", role=\"dataNode\"} > 0)"
    }
   ]
  },
  {
   "title": "ObjectNodeCount",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=\"$cluster\", app=\"$app\", role=\"objectnode\"})"
    }
   ]
  },
  {
   "title": "ClientCount",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{cluster=\"$cluster\", app=\"$app\", role=\"fuseclient\"} > 0)"
    }
   ]
  },
  {
   "title": "VolumeCount",
   "type": "singlestat",
   "description": "Cluster volume total count",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cfs_master_vol_count{app=\"$app\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ProcessStartTime",
   "type": "singlestat",
   "description": "Chubaofs process start time of selected instance",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{cluster=\"$cluster\", app=\"$app\", instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "DatanodeSize",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(cfs_master_dataNodes_total_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "TotalSize"
    },
    {
     "expr": "avg(cfs_master_dataNodes_used_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "UsedSize"
    },
    {
     "expr": "avg(cfs_master_dataNodes_increased_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "IncreasedSize"
    }
   ]
  },
  {
   "title": "MetanodeSize",
   "type": "bargauge",
   "description": "metanode size of total, used and increased.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "avg(cfs_master_metaNodes_total_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "TotalSize"
    },
    {
     "expr": "avg(cfs_master_metaNodes_used_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "UsedSize"
    },
    {
     "expr": "avg(cfs_master_metaNodes_increased_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "IncreasedSize"
    }
   ]
  },
  {
   "title": "VolumeTotalSize",
   "type": "bargauge",
   "description": "Top K total size of all volume",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "topk($topk, avg(cfs_master_vol_total_GB{app=\"$app\",cluster=\"$cluster\"}) by (volName))",
     "legendFormat": "{{volName}}"
    }
   ]
  },
  {
   "title": "DataNodeUsedRatio",
   "type": "gauge",
   "description": "Datanode used size ratio with total size",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(cfs_master_dataNodes_used_GB{app=\"$app\",cluster=\"$cluster\"})/ avg(cfs_master_dataNodes_total_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "DataNodeUsedRatio"
    }
   ]
  },
  {
   "title": "MetaNodeUsedRatio",
   "type": "gauge",
   "description": "Metanode used size ratio with total size",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "avg(cfs_master_metaNodes_used_GB{app=\"$app\",cluster=\"$cluster\"})/ avg(cfs_master_metaNodes_total_GB{app=\"$app\",cluster=\"$cluster\"})",
     "legendFormat": "MetaNodeUsedRatio"
    }
   ]
  },
  {
   "title": "DataNodeInactive",
   "type": "gauge",
   "description": "Datanode inactive count",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "avg(cfs_master_dataNodes_inactive{app=\"$app\", cluster=\"$cluster\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "MetaNodesInactive",
   "type": "gauge",
   "description": "Metanode inactive count",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "avg(cfs_master_metaNodes_inactive{app=\"$app\", cluster=\"$cluster\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "DiskError",
   "type": "singlestat",
   "description": "Disk Error count",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(delta(cfs_master_disk_error{app=\"$app\", cluster=\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "VolumeUsedRatio",
   "type": "bargauge",
   "description": "top k volume used ratio ",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "topk($topk, avg(cfs_master_vol_used_GB{app=\"$app\", cluster=\"$cluster\"}) by (volName) / avg(cfs_master_vol_total_GB{app=\"$app\", cluster=\"$cluster\"}) by (volName))",
     "legendFormat": "{{volName}}"
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "VolumeUsedSize",
   "type": "graph",
   "description": "top k volume used size",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($topk, avg(cfs_master_vol_used_GB{app=\"$app\",cluster=\"$cluster\"}) by (volName))",
     "legendFormat": "{{volName}}"
    }
   ]
  },
  {
   "title": "VolumeUsedRatio",
   "type": "graph",
   "description": "top k volume used ratio",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk($topk, cfs_master_vol_used_GB{app=\"$app\",cluster=\"$cluster\", instance=\"$master_instance\"}/cfs_master_vol_total_GB{app=\"$app\",cluster=\"$cluster\", instance=\"$master_instance\"})",
     "legendFormat": "{{volName}}"
    }
   ]
  },
  {
   "title": "VolumeSizeRate",
   "type": "graph",
   "description": "top k volume size rate",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(cfs_master_vol_used_GB{app=\"$app\",cluster=\"$cluster\", instance=\"$master_instance\"}[1m]))",
     "legendFormat": "{{volName}}"
    }
   ]
  },
  {
   "title": "[[vol]]",
   "type": "graph",
   "description": "Selected volume used/total size and used ratio",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cfs_master_vol_used_GB{app=\"$app\",cluster=\"$cluster\", volName=\"$vol\"})",
     "legendFormat": "UsedSize"
    },
    {
     "expr": "avg(cfs_master_vol_used_GB{app=\"$app\",cluster=\"$cluster\", volName=\"$vol\"})/avg(cfs_master_vol_total_GB{app=\"$app\",cluster=\"$cluster\", volName=\"$vol\"})",
     "legendFormat": "UsedRatio"
    }
   ]
  },
  {
   "title": "Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "master_nodes_invalide",
     "type": "graph",
     "description": "invalide master nodes",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, 1 - up{cluster=\"$cluster\", role=\"master\"} > 0 )",
       "legendFormat": "[[cluster]]_master_{{instance}}"
      }
     ]
    },
    {
     "title": "[[cluster]]_metanode_inactive",
     "type": "graph",
     "description": "invalide meta nodes",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 25 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, 1 - up{cluster=\"$cluster\", role=\"metanode\"} > 0 )",
       "legendFormat": "{{role}}_{{instance}}"
      }
     ]
    },
    {
     "title": "datanode_inactive",
     "type": "graph",
     "description": "invalide data nodes",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, 1 - up{cluster=\"$cluster\", role=\"dataNode\"}  > 0)",
       "legendFormat": "{{role}}_{{instance}}"
      }
     ]
    },
    {
     "title": "fuseclient_inactive",
     "type": "graph",
     "description": "invalide fuse clients",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 32 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, 1 - up{app=\"$app\", cluster=\"$cluster\", role=\"fuseclient\"}  > 0)",
       "legendFormat": "{{role}}_{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metanode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "[[mnOp]]:Time",
     "type": "graph",
     "description": "metanode op time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "repeat": "mnOp",
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk($topk, cfs_metanode_[[mnOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum( cfs_metanode_[[mnOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "[[mnOp]]:Ops",
     "type": "graph",
     "description": "metanode op count per second",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "repeat": "mnOp",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk($topk, cfs_metanode_[[mnOp]]_count{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum( cfs_metanode_[[mnOp]]_count{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Datanode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "[[dnOp]]:Time",
     "type": "graph",
     "description": "Datanode op time",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "repeat": "dnOp",
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk($topk, cfs_dataNode_[[dnOp]]{app=~\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(cfs_dataNode_[[dnOp]]{app=~\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "[[dnOp]]:Ops",
     "type": "graph",
     "description": "Datanode op count per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "repeat": "dnOp",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(cfs_dataNode_[[dnOp]]_count{app=~\"$app\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(cfs_dataNode_[[dnOp]]_count{app=~\"$app\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "sum"
      }
     ]
    }
   ]
  },
  {
   "title": "ObjectNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "[[obOp]]:Time",
     "type": "graph",
     "description": "Object node op time",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "repeat": "obOp",
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk($topk, cfs_objectnode_action_[[obOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(cfs_objectnode_action_[[obOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "[[obOp]]:Ops",
     "type": "graph",
     "description": "Object node op count per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "repeat": "obOp",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(cfs_objectnode_action_[[obOp]]_count{app=~\"$app\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(cfs_objectnode_action_[[obOp]]_count{app=~\"$app\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "sum"
      }
     ]
    }
   ]
  },
  {
   "title": "FuseClient",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "[[mnOp]]:Time",
     "type": "graph",
     "description": "fuse client use meta sdk op time",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "repeat": "mnOp",
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk($topk, cfs_rolefuseclient_[[mnOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(cfs_fuseclient_[[mnOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "[[mnOp]]:Ops",
     "type": "graph",
     "description": "fuse client use meta sdk op count per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "repeat": "mnOp",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(cfs_fuseclient_[[mnOp]]{app=\"$app\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(cfs_fuseclient_[[mnOp]]{app=\"$app\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "[[fuseOp]]:Time",
     "type": "graph",
     "description": "fuse client op time",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "repeat": "fuseOp",
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk($topk, cfs_fuseclient_[[fuseOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(cfs_fuseclient_[[fuseOp]]{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "[[fuseOp]]:Ops",
     "type": "graph",
     "description": "fuse op count per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "repeat": "fuseOp",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk($topk, cfs_fuseclient_[[fuseOp]]_count{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(cfs_fuseclient_[[fuseOp]]_count{app=\"$app\", cluster=\"$cluster\"})",
       "legendFormat": "sum"
      }
     ]
    }
   ]
  },
  {
   "title": "GoRuntime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_goroutines",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "y": 25 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(go_goroutines{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}[1m]))",
       "legendFormat": "{{role}}_{{instance}}"
      }
     ]
    },
    {
     "title": "go_threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 25 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "topk($topk, rate(go_threads{app=\"$app\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{role}}_{{instance}}"
      }
     ]
    },
    {
     "title": "gc_duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "seconds_{{quantile}}"
      },
      {
       "expr": "rate(go_gc_duration_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "gc_rate"
      }
     ]
    },
    {
     "title": "process_resident_memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\" }",
       "legendFormat": "resident_memory_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "process_virtual_memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "virtual_memory_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "process_virtual_memory_max",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_max_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "virtual_memory_max_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "open_fds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "y": 37 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "open_fds_{{instance}}"
      }
     ]
    },
    {
     "title": "max_fds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 37 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "max_fds_{{instance}}"
      }
     ]
    },
    {
     "title": "process_cpu",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\", role=\"$role\"}[1m])",
       "legendFormat": "cpu_seconds_{{instance}}"
      }
     ]
    },
    {
     "title": "alloc_bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "alloc_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "heap_alloc",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "heap_alloc_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "heap_inuse",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "heap_inuse_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "sys_bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "sys_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "other_sys",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "other_sys_bytes_{{instance}}"
      }
     ]
    },
    {
     "title": "mcache_sys",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{app=\"$app\", cluster=\"$cluster\", role=\"$role\"}",
       "legendFormat": "mcache_sys_bytes_{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}